In [4]:
import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
print(path)
print(os.listdir(path))

df = pd.read_csv(os.path.join(path, "results.csv"))
df.head()

c:\Users\ARW\anaconda3\envs\prediction\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

C:\Users\ARW\.cache\kagglehub\datasets\martj42\international-football-results-from-1872-to-2017\versions\129
['former_names.csv', 'goalscorers.csv', 'results.csv', 'shootouts.csv']

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [5]:
print(df.info())
df.head()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 49494 entries, 0 to 49493
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49494 non-null  str
 1   home_team   49494 non-null  str
 2   away_team   49494 non-null  str
 3   home_score  49481 non-null  float64
 4   away_score  49481 non-null  float64
 5   tournament  49494 non-null  str
 6   city        49494 non-null  str
 7   country     49494 non-null  str
 8   neutral     49494 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 3.1 MB
None

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [6]:
df["tournament"].value_counts().head(20)

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1053
Copa América                              869
African Cup of Nations                    845
AFC Asian Cup qualification               829
UEFA Nations League                       658
CECAFA Cup                                620
CFU Caribbean Cup qualification           606
Merdeka Tournament                        599
British Home Championship                 523
CONCACAF Nations League                   422
AFC Asian Cup                             421
Gold Cup                                  420
Gulf Cup                                  410
Island Games                              394
UEFA Euro                                 388
Asian Games                               368
Name: count, dtype: int64

In [ ]:
# convert to home score results
import numpy as np

df["home result"] = np.where(df["home_score"] > df["away_score"], 2,   # home win
               np.where(df["home_score"] == df["away_score"], 1,  # draw
                0)) # home loss
print(df["home result"].value_counts(normalize=True).mul(100).round(2)) # percentage of each result

home result
2    48.99
0    28.27
1    22.74
Name: proportion, dtype: float64

In [ ]:
# rank by datetime
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").reset_index(drop=True)
df[["date","home_team","away_team", "home result"]].head()

        date home_team away_team  home result
0 1872-11-30  Scotland   England            1
1 1873-03-08   England  Scotland            2
2 1874-03-07  Scotland   England            2
3 1875-03-06   England  Scotland            1
4 1876-03-04  Scotland   England            2

In [29]:
print(df["date"].min())
print(df["date"].max())

1872-11-30 00:00:00
2026-07-04 00:00:00