## kagglehub dataset import
https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017/data

In [3]:
import kagglehub
import os
import pandas as pd
import shutil

# import data with kagglehub
path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
print(path)
print(os.listdir(path))

# copy the freshly downloaded files into your project's data/raw folder
raw_dir = "data/raw"
os.makedirs(raw_dir, exist_ok=True)
for fname in ["results.csv", "shootouts.csv"]:
    shutil.copy(os.path.join(path, fname), os.path.join(raw_dir, fname))

C:\Users\ARW\.cache\kagglehub\datasets\martj42\international-football-results-from-1872-to-2017\versions\132
['former_names.csv', 'goalscorers.csv', 'results.csv', 'shootouts.csv']

In [ ]:
# import the results.csv data into a pandas dataframe and filter for matches after 1993-01-01
df_results = pd.read_csv(os.path.join(path, "results.csv"))

df_results = pd.read_csv("../data/raw/results.csv") # bc i added the last few matches manually to the raw data file
df_results = df_results[df_results["date"] >= "1993-01-01"]
df_results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
18708,1993-01-01,Ghana,Mali,1.0,1.0,Friendly,Libreville,Gabon,True
18709,1993-01-02,Gabon,Burkina Faso,1.0,1.0,Friendly,Libreville,Gabon,False
18710,1993-01-02,Kuwait,Lebanon,2.0,0.0,Friendly,Kuwait City,Kuwait,False
18711,1993-01-03,Burkina Faso,Mali,1.0,0.0,Friendly,Libreville,Gabon,True
18712,1993-01-03,Gabon,Ghana,2.0,3.0,Friendly,Libreville,Gabon,False

:

In [ ]:
# import the shootouts.csv data into a pandas dataframe
df_shootouts = pd.read_csv(os.path.join(path, "shootouts.csv"))

df_shootouts = pd.read_csv("../data/raw/shootouts.csv") # bc i added the last few matches manually to the raw data file
df_shootouts.head()

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

:

:

:

:

In [ ]:
# merge the shootouts data into the results data
df_results = pd.read_csv("../data/raw/results.csv")
df_shootouts = pd.read_csv("../data/raw/shootouts.csv")
df_results = df_results[df_results["date"] >= "1993-01-01"] # clip by dates

df_FINAL_RESULTS = df_results.merge(
    df_shootouts[
        ["date", "home_team", "away_team", "winner"]
    ],
    on=["date", "home_team", "away_team"],
    how="left",
)

:

:

:

:

In [ ]:
df_FINAL_RESULTS["winner"].notna().sum()

np.int64(511)

:

:

:

:

In [ ]:
# no duplicate matches created by merge
len(df_FINAL_RESULTS) == len(df_results)

True

:

:

:

:

In [ ]:
# number of shootout matches
df_FINAL_RESULTS["winner"].notna().sum()

np.int64(511)

:

:

:

:

In [ ]:
# inspect a few shootout matches
df_FINAL_RESULTS.loc[
    df_FINAL_RESULTS["winner"].notna(),
    [
        "date",
        "home_team",
        "away_team",
        "tournament",
        "home_score",
        "away_score",
        "winner",
    ],
].tail(20)

,date,home_team,away_team,tournament,home_score,away_score,winner
30315,2025-11-26,Oman,Somalia,Arab Cup qualification,0.0,0.0,Oman
30318,2025-11-26,Comoros,Yemen,Arab Cup qualification,4.0,4.0,Comoros
30346,2025-12-12,Algeria,United Arab Emirates,Arab Cup,1.0,1.0,United Arab Emirates
30387,2026-01-03,Mali,Tunisia,African Cup of Nations,1.0,1.0,Mali
30399,2026-01-14,Morocco,Nigeria,African Cup of Nations,0.0,0.0,Morocco
30400,2026-01-17,Egypt,Nigeria,African Cup of Nations,0.0,0.0,Nigeria
30423,2026-03-26,Wales,Bosnia and Herzegovina,FIFA World Cup qualification,1.0,1.0,Bosnia and Herzegovina
30428,2026-03-26,Czech Republic,Republic of Ireland,FIFA World Cup qualification,2.0,2.0,Czech Republic
30463,2026-03-27,Kenya,Estonia,FIFA Series,1.0,1.0,Estonia
30481,2026-03-28,Namibia,Comoros,FIFA Series,0.0,0.0,Namibia
30497,2026-03-30,Azerbaijan,Sierra Leone,FIFA Series,1.0,1.0,Azerbaijan
30500,2026-03-30,Cape Verde,Finland,FIFA Series,1.0,1.0,Cape Verde
30504,2026-03-30,Gabon,Trinidad and Tobago,FIFA Series,2.0,2.0,Gabon
30505,2026-03-30,Uzbekistan,Venezuela,FIFA Series,0.0,0.0,Uzbekistan
30544,2026-03-31,Bosnia and Herzegovina,Italy,FIFA World Cup qualification,1.0,1.0,Bosnia and Herzegovina
30547,2026-03-31,Czech Republic,Denmark,FIFA World Cup qualification,2.0,2.0,Czech Republic
30656,2026-06-06,Lithuania,Latvia,Baltic Cup,1.0,1.0,Lithuania
30771,2026-06-29,Germany,Paraguay,FIFA World Cup,1.0,1.0,Paraguay
30772,2026-06-29,Netherlands,Morocco,FIFA World Cup,1.0,1.0,Morocco
30782,2026-07-03,Australia,Egypt,FIFA World Cup,1.0,1.0,Egypt

:

:

:

:

In [ ]:
df_FINAL_RESULTS.to_csv("../data/processed/matches.csv", index=False)

:

:

:

: