## kagglehub dataset import
https://www.kaggle.com/datasets/martj42/international-football-results-from-1872-to-2017/data

In [20]:
import kagglehub
import os
import pandas as pd
import shutil

# import data with kagglehub
path = kagglehub.dataset_download("martj42/international-football-results-from-1872-to-2017")
print(path)
print(os.listdir(path))

# copy the freshly downloaded files into your project's data/raw folder
raw_dir = "data/raw"
os.makedirs(raw_dir, exist_ok=True)
for fname in ["results.csv", "shootouts.csv"]:
    shutil.copy(os.path.join(path, fname), os.path.join(raw_dir, fname))

C:\Users\ARW\.cache\kagglehub\datasets\martj42\international-football-results-from-1872-to-2017\versions\132
['former_names.csv', 'goalscorers.csv', 'results.csv', 'shootouts.csv']

In [ ]:
# import the results.csv data into a pandas dataframe and filter for matches after 1993-01-01
df_results = pd.read_csv(os.path.join(path, "results.csv"))
df_results = df_results[df_results["date"] >= "1993-01-01"]
df_results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
18708,1993-01-01,Ghana,Mali,1.0,1.0,Friendly,Libreville,Gabon,True
18709,1993-01-02,Gabon,Burkina Faso,1.0,1.0,Friendly,Libreville,Gabon,False
18710,1993-01-02,Kuwait,Lebanon,2.0,0.0,Friendly,Kuwait City,Kuwait,False
18711,1993-01-03,Burkina Faso,Mali,1.0,0.0,Friendly,Libreville,Gabon,True
18712,1993-01-03,Gabon,Ghana,2.0,3.0,Friendly,Libreville,Gabon,False

In [ ]:
# import the shootouts.csv data into a pandas dataframe
df_shootouts = pd.read_csv(os.path.join(path, "shootouts.csv"))
df_shootouts.head()

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

In [ ]:
# number of tournament types in the dataset
df_results["tournament"].value_counts().head(50)

tournament
Friendly                                 10211
FIFA World Cup qualification              6821
UEFA Euro qualification                   1991
African Cup of Nations qualification      1745
UEFA Nations League                        658
AFC Asian Cup qualification                613
African Cup of Nations                     606
FIFA World Cup                             597
CFU Caribbean Cup qualification            453
CONCACAF Nations League                    422
Gold Cup                                   404
CECAFA Cup                                 383
Island Games                               368
COSAFA Cup                                 354
Copa América                               352
UEFA Euro                                  308
AFF Championship                           291
AFC Asian Cup                              282
Gulf Cup                                   234
CFU Caribbean Cup                          187
SAFF Cup                                   162
UNCAF Cup                                  155
Confederations Cup                         136
EAFF Championship                          130
WAFF Championship                          114
Oceania Nations Cup                        113
Arab Cup                                   102
CONIFA World Football Cup                  101
King's Cup                                  94
Asian Games                                 94
Southeast Asian Games                       92
AFC Challenge Cup qualification             92
Gold Cup qualification                      88
AFC Challenge Cup                           87
Indian Ocean Island Games                   86
Pacific Games                               75
Amílcar Cabral Cup                          73
Cyprus International Tournament             70
South Pacific Games                         68
CONCACAF Nations League qualification       68
Kirin Cup                                   64
AFF Championship qualification              62
Muratti Vase                                61
Baltic Cup                                  61
Viva World Cup                              60
FIFA Series                                 57
Nehru Cup                                   55
CONIFA European Football Cup                49
Coupe de l'Outre-Mer                        42
Malta International Tournament              40
Name: count, dtype: int64

In [ ]:
# list of unique tournament types in the dataset
sorted(df_results["tournament"].unique())

['ABCS Tournament',
 'AFC Asian Cup',
 'AFC Asian Cup qualification',
 'AFC Challenge Cup',
 'AFC Challenge Cup qualification',
 'AFC Solidarity Cup',
 'AFF Championship',
 'AFF Championship qualification',
 'ASEAN Championship',
 'ASEAN Championship qualification',
 'African Cup of Nations',
 'African Cup of Nations qualification',
 'Afro-Asian Games',
 'Al Ain International Cup',
 'Amílcar Cabral Cup',
 'Arab Cup',
 'Arab Cup qualification',
 'Asian Games',
 'Atlantic Heritage Cup',
 'Baltic Cup',
 'Benedikt Fontana Cup',
 'CAFA Nations Cup',
 'CECAFA Cup',
 'CFU Caribbean Cup',
 'CFU Caribbean Cup qualification',
 'CONCACAF Nations League',
 'CONCACAF Nations League qualification',
 'CONCACAF Series',
 'CONIFA Africa Football Cup',
 'CONIFA Asia Cup',
 'CONIFA European Football Cup',
 'CONIFA South America Football Cup',
 'CONIFA World Cup qualification',
 'CONIFA World Football Cup',
 'CONIFA World Football Cup qualification',
 'CONMEBOL–UEFA Cup of Champions',
 'COSAFA Cup',
 'COSAFA Cup qualification',
 'Canadian Shield',
 'ConIFA Challenger Cup',
 'Confederations Cup',
 'Copa América',
 'Copa América qualification',
 'Copa Confraternidad',
 'Copa Paz del Chaco',
 'Copa del Pacífico',
 'Corsica Cup',
 "Coupe de l'Outre-Mer",
 'Cup of Ancient Civilizations',
 'Cyprus International Tournament',
 'Diamond Jubilee International Football Tournament',
 'Dragon Cup',
 'Dunhill Cup',
 'Dynasty Cup',
 'EAFF Championship',
 'EAFF Championship qualification',
 'ELF Cup',
 'East Asian Games',
 'FIFA Series',
 'FIFA World Cup',
 'FIFA World Cup qualification',
 'FIFI Wild Cup',
 'Four Nations Tournament',
 "Four Nations' Cup",
 'Friendly',
 'Gold Cup',
 'Gold Cup qualification',
 'Gulf Cup',
 'Hungary Heritage Cup',
 'Indian Ocean Island Games',
 'Inter Games',
 'Intercontinental Cup',
 'International Tournament of Peoples, Cultures and Tribes',
 'Island Games',
 'Joe Robbie Cup',
 'Jordan International Tournament',
 'King Hassan II Tournament',
 "King's Cup",
 'Kirin Challenge Cup',
 'Kirin Cup',
 'Korea Cup',
 'Lunar New Year Cup',
 "MSG Prime Minister's Cup",
 'Mahinda Rajapaksa Cup',
 'Malta International Tournament',
 'Mapinduzi Cup',
 'Marianas Cup',
 'Mauritius Four Nations Cup',
 'Melanesia Cup',
 'Merdeka Tournament',
 'Miami Cup',
 'Millennium Cup',
 'Morocco, Capital of African Football',
 'Mukuru 4 Nations',
 'Muratti Vase',
 'Nations Cup',
 'Navruz Cup',
 'Nehru Cup',
 'Niamh Challenge Cup',
 'Nile Basin Tournament',
 'Nordic Championship',
 'OSN Cup',
 'Oceania Nations Cup',
 'Oceania Nations Cup qualification',
 'Outrigger Challenge Cup',
 'Pacific Games',
 'Pacific Mini Games',
 'Palestine International Championship',
 'Philippine Peace Cup',
 "Prime Minister's Cup",
 'SAFF Cup',
 'SKN Football Festival',
 'Simba Tournament',
 'Soccer Ashes',
 'South Asian Games',
 'South Asian Super Cup',
 'South Pacific Games',
 'South Pacific Mini Games',
 'Southeast Asian Games',
 'Superclásico de las Américas',
 'TIFOCO Tournament',
 'The Other Final',
 'Three Nations Cup',
 'Tournoi de France',
 'Trans-Tasman Cup',
 'Tri Nation Tournament',
 'Tri-Nations Cup',
 'Tri-Nations Series',
 'Tynwald Hill Tournament',
 'UEFA Euro',
 'UEFA Euro qualification',
 'UEFA Nations League',
 'UNCAF Cup',
 'UNIFFAC Cup',
 'USA Cup',
 'United Arab Emirates Friendship Tournament',
 'Unity Cup',
 'VFF Cup',
 'Viva World Cup',
 'WAFF Championship',
 'Windward Islands Tournament',
 'World Unity Cup']

In [ ]:
# number of unique tournament types in the dataset
df_results["tournament"].nunique()

142

In [40]:
# merge the shootouts data into the results data
df_results = pd.read_csv("data/raw/results.csv")
df_shootouts = pd.read_csv("data/raw/shootouts.csv")

df_results = df_results[df_results["date"] >= "1993-01-01"]

df_FINAL_RESULTS = df_results.merge(
    df_shootouts[
        ["date", "home_team", "away_team", "winner"]
    ],
    on=["date", "home_team", "away_team"],
    how="left",
)

In [41]:
df_FINAL_RESULTS["winner"].notna().sum()

np.int64(511)

In [43]:
# No duplicate matches created by merge
len(df_FINAL_RESULTS) == len(df_results)

# Number of shootout matches
df_FINAL_RESULTS["winner"].notna().sum()

# Inspect a few shootout matches
df_FINAL_RESULTS.loc[
    df_FINAL_RESULTS["winner"].notna(),
    [
        "date",
        "home_team",
        "away_team",
        "home_score",
        "away_score",
        "winner",
    ],
].head(20)

,date,home_team,away_team,home_score,away_score,winner
29,1993-01-23,Japan,Switzerland,1.0,1.0,Switzerland
80,1993-02-20,Finland,Estonia,0.0,0.0,Finland
86,1993-02-24,Argentina,Denmark,1.0,1.0,Argentina
360,1993-05-27,Bolivia,Paraguay,2.0,1.0,Bolivia
362,1993-05-28,Martinique,Saint Kitts and Nevis,1.0,1.0,Martinique
370,1993-05-30,Jamaica,Martinique,0.0,0.0,Martinique
447,1993-06-17,Singapore,Myanmar,3.0,3.0,Singapore
479,1993-06-26,Colombia,Uruguay,1.0,1.0,Colombia
481,1993-06-27,Brazil,Argentina,1.0,1.0,Argentina
488,1993-07-01,Colombia,Argentina,0.0,0.0,Argentina
594,1993-08-15,Australia,Canada,2.0,1.0,Australia
699,1993-10-24,Burundi,Guinea,0.0,0.0,Guinea
792,1993-12-26,Nepal,India,2.0,2.0,Nepal
820,1994-01-29,Burkina Faso,Guinea,1.0,1.0,Burkina Faso
924,1994-04-06,Nigeria,Ivory Coast,2.0,2.0,Nigeria
1103,1994-07-05,Mexico,Bulgaria,1.0,1.0,Bulgaria
1117,1994-07-10,Romania,Sweden,2.0,2.0,Sweden
1123,1994-07-17,Brazil,Italy,0.0,0.0,Brazil
1374,1994-12-08,Tanzania,Uganda,2.0,2.0,Tanzania
1422,1995-01-10,Denmark,Mexico,1.0,1.0,Denmark

In [44]:
df_FINAL_RESULTS.to_parquet(
    "../data/processed/matches.parquet",
    index=False,
)